MySQL:
  Host: localhost
  User: root
  Password: ''
  Database: testbd
Settings:
  VKToken: ""
  DatabaseName: "Auth"
  NameColumn: "Name"
Strings:
  AuthString: "Введите код из сообщения ВКонтакте"
  OnLoginString: "Код верный"